### ISSUE TITLE
savior改版秘法符文日常變周常

### ISSUE THREAD

**Issue by HikariCalyx** [spd789562/MapleStory-Arcane-Symbol-Calculator#18]
目前猜測該改版會在6月21日實裝CMS和TMS。
届時有打算改變這個嗎？

具體細節會在韓測放出之後給出。

**Comment by HikariCalyx** [comment]
![0](https://media.discordapp.net/attachments/312354082356592641/1053127507232182312/image.png)

**Comment by spd789562** [comment]
理論上是要改，而且要分 branch，只是組隊類的變周常就有點難搞了...有點不是很確定要怎麼呈現是在某個周區間 >_>

**Comment by spd789562** [comment]
https://maplestory-arcane-symbol-calculator-git-featur-6059ee-spd789562.vercel.app/
似乎也沒我想的那麼麻煩，稍微改一下算法而已
也順便更新主分支增加曝光度了，希望到時候會有人測XDDDD

**Comment by HikariCalyx** [comment]
提醒一下，TMS已经比CMS先更新savior改版，所以能看一下怎么更新吗？

**Comment by spd789562** [comment]
目前看起來是沒什麼問題，不過我忘記得改一些組隊任務的文字了

**Comment by HikariCalyx** [comment]
是的，只有前两个是组队任务，后面全是单人任务。

**Comment by spd789562** [comment]
突然覺得好像不用管XDDDD，就這樣好了
還得煩惱 new age 的楓幣公式呢...
