### ISSUE TITLE
AUT触媒计算不正确

### ISSUE THREAD

**Issue by HikariCalyx** [spd789562/MapleStory-Arcane-Symbol-Calculator#24]
实际是减少40%而不是20%，例如下面实际是减少到18而不是24。
![image](https://github.com/spd789562/MapleStory-Arcane-Symbol-Calculator/assets/29157608/864d682b-3990-4ed3-ba0d-793446ee72c5)
![image](https://github.com/spd789562/MapleStory-Arcane-Symbol-Calculator/assets/29157608/b96af3cb-a3f0-469a-ba9f-a70caf6da1de)

**Comment by spd789562** [comment]
感謝回報，我真的忘了不一樣了
