### ISSUE TITLE
新增新的真实符文：塔拉哈特

### ISSUE THREAD

**Issue by HikariCalyx** [spd789562/MapleStory-Arcane-Symbol-Calculator#25]
![Eqp_Grand_Sacred_Symbol_Tallahart](https://github.com/user-attachments/assets/1bc736dd-94cd-4630-b91f-db05fd753801)
该地区的英文名为 Tallahart。

https://namu.wiki/w/%EC%96%B4%EC%84%BC%ED%8B%B1%ED%8F%AC%EC%8A%A4?from=%EC%96%B4%EC%84%BC%ED%8B%B1%20%ED%8F%AC%EC%8A%A4#fn-9

如你所听说的一样，该真实符文不加主属性，只加经验值获取量、枫掉、掉宝。每日给10个。具体的枫币消耗量可以暂缓加入，因为公式还未正式确认。

**Comment by HikariCalyx** [comment]
公式已确认，可以考虑添加了。

**Comment by spd789562** [comment]
不過這東西挺困擾的，基於他是加成其他屬性，不知道該顯示在哪邊

**Comment by spd789562** [comment]
剛剛試了一下，和其他真實符紋的公式一樣，常數帶 39.8 就行，再來問題就是要怎麼放了

**Comment by spd789562** [comment]
已新增，不過有點醜醜就是
